### PR TITLE
fix global undefined on service worker

### PR DESCRIPTION
**Pull request by smeng9**
Fixes https://github.com/nodejs/readable-stream/issues/487

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Do you think it would be possible to add a unit test under https://github.com/nodejs/readable-stream/tree/main/test/browser?

**Comment by smeng9** [comment]
What kind of tests are we expected to run for this case? Do you mean add a runner-worker.mjs for service worker?

**Comment by mcollina** [comment]
It should run a service worker and get back some data.

**Comment by smeng9** [comment]
Hi @mcollina the worker setup seems is way more complicated than I thought.

Also this pull request should only target v3.6.0 https://github.com/nodejs/readable-stream/blob/bed7ffa274f5b9e6d0d5c22369e6fe825ded03d2/lib/_stream_readable.js where v4 seems does not have such issue.

Unfortunately, some of our dependencies still uses v3.

**Comment by mcollina** [comment]
Can you target the v3.x line with your PR then? The build scripts were redone between them.

**Comment by smeng9** [comment]
Hi @mcollina I cannot find the 3.x branch here https://github.com/nodejs/readable-stream/branches/stale?page=1 to target my commit with. Can you help to create a 3.x branch in this repo? Thanks!

Then I can fork it and create a merge.

**Pull request closed without merging**
