### PR TITLE
build/test-replacements.js: fix typo.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by vweevers** [comment]
@mcollina I was just looking at that; the typo (and surrounding code) doesn't exist in node core.

It seems our tests are a bit outdated? https://github.com/nodejs/node/blob/master/test/parallel/test-stream2-unpipe-drain.js

**Comment by XhmikosR** [comment]
I have already made upstream patches and trying to fix the typos across the whole ecosystem :)

https://github.com/nodejs/node/pull/29075

**Comment by mcollina** [comment]
@vweevers The tests are pulled from the Node 10.x release, as well as the rest of the code.

We might do a semver-major bump when Node 12 goes LTS.

@XhimikosR can you remove the test change from this PR?

**Comment by XhmikosR** [comment]
@mcollina: done

**Comment by XhmikosR** [comment]
@mcollina friendly ping

**Comment by mcollina** [comment]
Thanks!

**Pull request merged**
