### PR TITLE
build for 5.0.0

### PR DESCRIPTION
**Pull request by calvinmetcalf**
includes the buffer optimization and an edge case fix for piping

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
and we are green, @mafintosh this has the buffer.concat optimization

**Comment by mafintosh** [comment]
awesome! :+1: from me

**Comment by calvinmetcalf** [comment]
rebased and still green going to merge and publish

**Comment by calvinmetcalf** [comment]
03ca5ad8bd06fbadc8260455342bd6f64da348bd

**Comment by yoshuawuyts** [comment]
🚋🚋🚋🚋🚋🚋🚋🎉

**Pull request closed without merging**
