### PR TITLE
build for 5.6.0

### PR DESCRIPTION
**Pull request by calvinmetcalf**

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
and we are actually green! https://travis-ci.org/nodejs/readable-stream/builds/109629800

**Comment by calvinmetcalf** [comment]
can I get a :+1: on this from anyone in @nodejs/streams so I can start work on v5.7.0?

**Comment by mcollina** [comment]
LGTM, but I'm not in @nodejs/streams (how can I join?)

**Comment by calvinmetcalf** [comment]
that is a very good question looks like @chrisdickinson  or @rvagg would have to invite you

**Comment by rvagg** [comment]
Done, but I think if you click through to @nodejs/streams you can request membership at least.

@calvinmetcalf could do with a hand around here I think! Thanks @mcollina.

**Comment by mcollina** [comment]
Thanks @rvagg! It's not clear _how_ you join a WG for the docs.

**Comment by rvagg** [comment]
that's up to the WG to figure out, some are more open than others by nature

**Comment by mcollina** [comment]
@rvagg of course! :) But even that is not written anywhere.

**Pull request merged**
