### PR TITLE
Node 8

### PR DESCRIPTION
**Pull request by calvinmetcalf**

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
ok I need to fix the Stream._isUint8Array and similar stuff

**Comment by mcollina** [comment]
There is a PR waiting to me merged for this.

cc @addaleax for the other things

**Comment by calvinmetcalf** [comment]
I know how to add them I just didn't get around to it before I went home

**Comment by calvinmetcalf** [comment]
and we are green (though I need to rebase it on top of the other pull)

**Comment by mcollina** [comment]
@calvinmetcalf I've added #255 commit in here. It should be good to go.

**Comment by calvinmetcalf** [comment]
ok bumped it so it should hopfully build

**Comment by mcollina** [comment]
I think we should release it as 2.3.0. Let's do this next week, so that @nodejs/streams might have time to review it (I would also be at home and not traveling, in case we need to last-minute bugfixes)

**Comment by calvinmetcalf** [comment]
ok sounds good

**Comment by addaleax** [comment]
I looked over the patch and nothing seemed to stick out … I might not have time for a full review but this seems fine to me.

**Comment by addaleax** [comment]
We might want to include something like https://github.com/nodejs/node/pull/13760.

**Comment by mcollina** [comment]
I think we should wait for that to be released

**Comment by calvinmetcalf** [comment]
ok I'll plan on publishing this soon

**Pull request merged**
