### PR TITLE
reuse existing import of "stream"

### LINKED ISSUE #205: Reduce package size
From https://github.com/nodejs/readable-stream/pull/197#discussion_r61090554.

Having to download 2 MB extra makes this module unusable for most smaller modules.

Would be nice to find a way to not have to include those huge dependencies.

### PR DESCRIPTION
**Pull request by calvinmetcalf**
should fix #205

### CODE REVIEW

**Comment by mcollina** [comment]
LGTM. BTW, what's the status on our CITGM with this?

**Comment by calvinmetcalf** [comment]
ok will merge and publish, as for citgm no idea was in japan and dubai last week and was sick as a dog most of this week so I'm totally out of the loop.

**Comment by ahutchings** [comment]
This breaks browserify builds because the removed dependencies are still listed in package.json under browserify transforms. Should the browserify configuration be removed from package.json as well?

**Comment by calvinmetcalf** [comment]
fuck your right one sec

**Comment by calvinmetcalf** [comment]
thanks for the catch @ahutchings, unclear how that passed our tests which involve browserify...

**Comment by ahutchings** [comment]
No worries, thanks for the quick turnaround.

**Comment by calvinmetcalf** [comment]
np

**Comment by calvinmetcalf** [comment]
ok I'm going to depreciate 2.1.1 with the following message

  Version 2.1.1 has a misconfigured package.json and will likely not work with browserify, If you aren't directly requiring readable-stream use `npm ls readable-stream@2.1.1` to find out what package is.

since this is reversible I'm going to just go ahead and do this.

Not going to unpublish since from experience that causes a lot of problems, but we can if we want latter

**Pull request merged**
