### PR TITLE
Updated to node v7.10.0.

### PR DESCRIPTION
**Pull request by mcollina**
cc @nodejs/streams

### CODE REVIEW

**Comment by mcollina** [comment]
@calvinmetcalf there was a verify high number of breakages due to npm and some things that were not transpiled.

**Comment by mcollina** [comment]
@calvinmetcalf CI is badly broken :( https://travis-ci.org/nodejs/readable-stream/jobs/237500260

**Comment by calvinmetcalf** [comment]
ah looks like they stoped supporting 0.10?

**Comment by mcollina** [comment]
@zkat can you have a look here? it used to work :(.

**Comment by zkat** [comment]
@mcollina we do not support, at all, any versions of node older than node@4. Only node versions still in maintenance are targeted, and we've started intentionally breaking compatibility now.

**Comment by mcollina** [comment]
@zkat You mean that `npm@lts` is not supported anymore? what about `npm@latest-3`?

**Comment by zkat** [comment]
@mcollina I guess lts and 3 would probably still work, but this stuff isn't really supposed to run on `node@0.10`. It looks like we officially took out `0.10` support with `npm@4.0`, and dropped `0.12` support as of `npm@4.1.2`.

**Comment by mcollina** [comment]
@zkat we are now using npm@2 and npm@latest-3 in the unsupported versions of Node. Things are passing again now :).

**Comment by mcollina** [comment]
@calvinmetcalf I disabled the new `test/parallel/test-stream-unpipe-event.js` in Node v0.8 as it was not passing. I don't think there is any value in fixing it.

**Comment by calvinmetcalf** [comment]
ok what was the issue with unpipe events ?

**Comment by mcollina** [comment]
This is the relative PR: https://github.com/nodejs/node/pull/11876. I do not know why it does not pass on node 0.8.

**Comment by calvinmetcalf** [comment]
ok looks like the test may have been wonky? I don't know lgtm

**Pull request merged**
