### PR TITLE
testing to see if Array.isArray really is required

### PR DESCRIPTION
**Pull request by calvinmetcalf**
#212

### CODE REVIEW

**Comment by mcollina** [comment]
It seems fine, LGTM.

**Comment by calvinmetcalf** [comment]
I am somewhat hesitant just that there may be some platforms that we can't test on that it does work enough on but would break if we remove this

**Comment by mcollina** [comment]
Let's stick a semver-major label, and we'll merge when we bump the major.
Il giorno lun 23 mag 2016 alle 13:44 Calvin Metcalf <
notifications@github.com> ha scritto:

**Comment by calvinmetcalf** [comment]
but why should we bother, it's like 3 lines, there is very little upside

**Comment by mafintosh** [comment]
I agree with @calvinmetcalf that I dont see the upside in merging this

**Pull request closed without merging**
