### PR TITLE
Build from Node v10.15.3

### PR DESCRIPTION
**Pull request by mcollina**
Fixes https://github.com/nodejs/readable-stream/issues/387

### CODE REVIEW

**Comment by mcollina** [comment]
@vweevers can you take a look?

**Comment by vweevers** [comment]
Short on time, maybe tomorrow, else next week

**Comment by mcollina** [comment]
cc @lpinca?

**Comment by lpinca** [comment]
I'm not familiar enough with this codebase to comment on or approve this PR, sorry Matteo.

**Pull request merged**
