### PR TITLE
Avoid caret during installation, and added node v0.6 to .travis.yml

### PR DESCRIPTION
**Pull request by mcollina**
For some context, I would like mysql to use the latest readable-stream: https://github.com/mysqljs/mysql/pull/1677

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
dependencies of dependencies are also an issue, which is why I did it this way

**Comment by mcollina** [comment]
Updated, this should work also on older versions of NPM.

**Comment by mcollina** [comment]
@calvinmetcalf yes. But it might allow the mysql module to upgrade to v2. We don't expect buffer-shims to change at any point in time either.

**Comment by AdriVanHoudt** [comment]
I don't see the node 0.6 travis change in the files changed as stated in the title or is that just me?

**Comment by mcollina** [comment]
I updated the title. We cannot really run our tests on Node v0.6.
Depending using `~` simplify backporting to old NPM versions. The tests passes, but our own test dependencies cannot be installed there anymore.

**Pull request merged**
