### PR TITLE
browserify compatibility

### PR DESCRIPTION
**Pull request by zertosh**
Fixes https://github.com/substack/node-browserify/issues/1312. After this I can bump stream-browserify to ^2.0.0 in browserify.

### CODE REVIEW

**Comment by zertosh** [comment]
The travis failures seem to be a saucelabs credentials issue

**Comment by calvinmetcalf** [comment]
I'm away from a computer for the next two weeks so can't merge this or publish but it looks good so of @rvagg or @isaacs could merge and publish it that would be very helpful

**Comment by dcousens** [comment]
LGTM

**Comment by calvinmetcalf** [comment]
so the regex actually has to be updated not the result of it so I opened #153 which should be doing exactly the same this as this just via the updated regex

**Comment by calvinmetcalf** [comment]
merged and published as 2.0.2

**Comment by zertosh** [comment]
@calvinmetcalf Ah ok. Thanks!

**Pull request closed without merging**
