### PR TITLE
Build 8.9.4

### LINKED ISSUE #316: sinon/lolex fake timers broken when used with this
Consider the following mocha test file

```js
var lolex = require('lolex');
var through = require('through2');

describe('a bug', function() {
  var clock;
  before(function() {
    clock = lolex.install({toFake: [ 'setImmediate', 'nextTick' ]});
  });
  after(function() {
    clock.uninstall();
  });

  it('does not work well with lolex', function(done) {
    var stream = through.obj();
    stream.on('data', function() {
      stream.on('end', function() {

        console.log('creating stream2')
        var stream2 = through.obj();
        stream2.on('data', function() {
          stream2.on('end', function() {
            console.log('OK')
            done();            
          });
          setImmediate(function() {
            stream2.end()
          });
        });
        stream2.emit('data')

      });
      stream.end();
    });
    stream.emit('data');

    clock.runAll()
  });

});

```

When the `clock` calls are removed and this runs using regular time this runs and finishes as expected and without errors. However when running with lolex `install`ed it just hangs after logging `creating stream2`. This is due to https://github.com/nodejs/readable-stream/blob/d6c391d7101946c8b8b97914fc46fd3322c450d1/lib/_stream_readable.js#L983 which retains a reference to the non swapped out version of `process.nextTick` due to use of `process-nextick-args` https://github.com/nodejs/readable-stream/blob/d6c391d7101946c8b8b97914fc46fd3322c450d1/lib/_stream_readable.js#L26

A simple solution can be swapping `require('process-nextick-args')` with `require('./process-nextick-args')` which can look something like this:

```js
//  ./process-nextick-args
var nextTickNeedsPatching = (
  !process.version ||
  process.version.indexOf('v0.') === 0 ||
  process.version.indexOf('v1.') === 0 && process.version.indexOf('v1.8.') !== 0
);

var processNextTick = function(fn, a, b, c) {
  return !nextTickNeedsPatching ? process.nextTick(fn, a, b, c) :
  process.nextTick(function() {
    fn(a, b, c);
  });
  
}
```

Does that sound like a reasonable solution?

### PR DESCRIPTION
**Pull request by mcollina**
As titled.

I have also updated process-nextick-args.
Fixes #316.

### CODE REVIEW

**Comment by mcollina** [comment]
```
> [secure]@2.3.3 write-zuul /home/travis/build/nodejs/[secure]
> printf "ui: tape
browsers:
  - name: $BROWSER_NAME
    version: $BROWSER_VERSION
">.zuul.yml
- testing: microsoftedge @ Windows 10: 16
- restarting: <microsoftedge 16 on Windows 10>
- restarting: <microsoftedge 16 on Windows 10>
- failed: <microsoftedge 16 on Windows 10> (0 failed, 0 passed)
1 browser(s) failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! [secure]@2.3.3 browser: `npm run write-zuul && zuul --browser-retries 2 -- test/browser.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the [secure]@2.3.3 browser script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-02-08T09_57_28_455Z-debug.log
```

localtunnel/saucelabs is not really working atm.

**Comment by vweevers** [comment]
@mcollina FWIW memdown had similar issues, that disappeared when we switched to Sauce Connect (https://github.com/Level/memdown/pull/81) - though it depends on an as-of-yet unmerged change to `zuul`.

**Comment by mcollina** [comment]
@vweevers considering that zuul is not really well maintained, how about we spin up a new project for that? I would prefer to depend on something from npm and not from a github account.

**Comment by vweevers** [comment]
SGTM! Can we reduce its scope (Sauce Connect only) to lower the maintenance cost?

**Comment by mcollina** [comment]
> SGTM! Can we reduce its scope (Sauce Connect only) to lower the maintenance cost?

Yes definitely.

**Comment by yoshuawuyts** [comment]
Scaling CI down to just Sauce Connect sounds good! ~ have been frustrated with Zuul for a while too now; having a more reliable solution is definitely a step forward.

**Comment by vweevers** [comment]
I should have knocked on wood.. Sauce Labs is now also failing for memdown, with an error similar to https://github.com/nodejs/readable-stream/pull/320#issuecomment-364096828. But I think forking zuul to work with Sauce Connect is still a good idea, as it at least removes localtunnel as a point of failure. If you agree I'll open an repo to continue discussion there.

**Comment by mcollina** [comment]
@vweevers I also spoke with @feross whom agreed on helping out. I would say go ahead and create a repo and add all of us, I think we can build something that it's easy to maintain.

**Pull request merged**
