### PR TITLE
first run at 6.4.0

### PR DESCRIPTION
**Pull request by calvinmetcalf**
and there is a new es6 feature being used in tests and a couple more fixtures!

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
and a few tests that use encodings not all versions of node have, no actual changes to streams here so no rush

**Comment by calvinmetcalf** [comment]
ok the issue with the preprocessing test was basically it was relying on some specific tty stuff that was kinda tangential to streams specifically

**Comment by calvinmetcalf** [comment]
if others are on the same page about being able to ditch that preprocess test I can merge this

**Comment by mcollina** [comment]
@calvinmetcalf LGTM

As a side note, that test is not targeting `readable-stream`, as it is using `fs`, `readline` and others`, so there is nothing we can fix here.

Can we avoid pulling it the next time? That test also relies on two `txt` files, those should be removed as well. It's really a test about `fs` and `readline` rather than streams.

As a side note, that test it was introduced by @vsemozhetbyt in https://github.com/nodejs/node/pull/7741 and https://github.com/nodejs/node/commit/ea725eda426add1d684c80f2c2c585cd2ca797c9

cc @addaleax

**Comment by calvinmetcalf** [comment]
oh right need to remove those

**Comment by calvinmetcalf** [comment]
we'd avoid pulling it in if it wasn't named 'stream' it's just a function of the fact that it was touching 3 diff modules and it had to pick one

**Comment by mcollina** [comment]
@calvinmetcalf we should move it then.

**Comment by addaleax** [comment]
I’m not sure what the process for pulling in tests is but if moving that one test in the node repo makes anything easier for anyone that shouldn’t be a problem?

**Comment by calvinmetcalf** [comment]
not a big deal any more, I just put something in the code that doesn't pull
it in

**Comment by calvinmetcalf** [comment]
this is a transient error, I'll plan on merging this latter if nobody objects

**Pull request merged**
