### PR TITLE
replace bind()

### PR DESCRIPTION
**Pull request by mscdex**
This is anticipation of Writable changes landing in https://github.com/nodejs/node/pull/6533

/cc @calvinmetcalf @mcollina

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
ok this works fine because we put it through babel to deal with the arrow functions, but I wonder why node core couldn't use the arrow function?

**Comment by mcollina** [comment]
`bind()` changed from being a v8 killer to be _faster_ than arrow functions from node v7+.

**Comment by mscdex** [comment]
@mcollina s/arrow functions/inline closures/

**Comment by mcollina** [comment]
@mscdex yes sorry. `bind()` is now faster than using function to wrap `this`.

**Comment by calvinmetcalf** [comment]
so readable stream is intended for use in all versions of node/multiple browsers so I'm not sure the wisdom of including optimizations for older platforms, chrome for instance will be negatively effected by this

**Comment by mscdex** [comment]
@calvinmetcalf Well, it's not just older node versions but also possibly other javascript engines that might not optimize the same things. I personally do not see a straight-forward solution because `readable-stream` is/could be used in so many different environments. If we leave the `bind()` it might work better in some environments worse in others, same goes for reverting its usage. The same also goes for https://github.com/nodejs/readable-stream/pull/255.

I just created these PRs because [@mcollina had mentioned in the upstream node PR](https://github.com/nodejs/node/pull/6533#issuecomment-268741141) that he considered performance changes to be breaking.

**Comment by mcollina** [comment]
@calvinmetcalf using `bind()` in node v0.10/v0.12 and the like can cause a *massive* slowdown. See https://github.com/Level/levelup/pull/139 as an example. If we want to play it safe, we should really benchmark this change on node v0.10-v6, and see if it impacts things. Or, we can do the change and avoid potential breakage (yes, I consider a major slowdown a breakage).

**Comment by mcollina** [comment]
We are going to merge this on the next update, as decided in #252

**Comment by mcollina** [comment]
Part of #262

**Pull request closed without merging**
