### PR TITLE
add microsoft edge to testing

### PR DESCRIPTION
**Pull request by calvinmetcalf**
#193

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
cool!

**Comment by mcollina** [comment]
There are couple of failures with 

```
Error: connection refused: localtunnel.me:35059 (check your firewall settings)
```

Something is wrong? Maybe it needs a timeout for the tunnel.

Unrelated, why travis data do not show up here?

**Comment by calvinmetcalf** [comment]
travis data doesn't show up here because there is no way to turn it on for this repo but not for all repos in the org, I don't know about the timeout might be a bug in zuul

**Comment by mcollina** [comment]
@calvinmetcalf are you sure about travis? was it discussed?

**Comment by calvinmetcalf** [comment]
yes I discussed it with @Fishrock123 on irc

**Comment by Fishrock123** [comment]
Wait, what about Travis and IRC?

**Comment by calvinmetcalf** [comment]
@Fishrock123 'travis data doesn't show up here because there is no way to turn it on for this repo but not for all repos in the org ...'

**Comment by Fishrock123** [comment]
oh right.

We should use @phillipj's bot that the website uses: https://github.com/nodejs-github-bot/github-bot

**Comment by calvinmetcalf** [comment]
what is that ?

**Comment by Fishrock123** [comment]
The website WG uses that bot to post travis statuses because they have the same problem.

**Comment by phillipj** [comment]
@calvinmetcalf https://github.com/nodejs/nodejs.org/issues/355#issuecomment-189020365

It should work out of the box, as this repo is in the same weird Travis state as nodejs.org. Meaning Travis picks up changes, but the inline integration with PR's doesn't work because of the 3rd party permission issue you mentioned earlier.

https://travis-ci.org/nodejs/readable-stream

I'll send you the webhook URL needed on IRC to make nodejs-github-bot add comments on every created PR about the Travis build status.

**Comment by calvinmetcalf** [comment]
ok thanks

**Comment by calvinmetcalf** [comment]
ok repushed to see if that was an intermittent failure

**Comment by calvinmetcalf** [comment]
this is green

**Pull request merged**
