### PR TITLE
update to node 5.1.0

### PR DESCRIPTION
**Pull request by calvinmetcalf**
only real updates are to the docs

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
rebased this to be based on #171 so we can get the perf boost that that pull brings, ready for review @nodejs/streams

**Comment by calvinmetcalf** [comment]
add a commit to include the result of calvinmetcalf/process-nextick-args#5 which should speed things up

**Comment by calvinmetcalf** [comment]
I don't know why the tests aren't being shown but they are fully green https://travis-ci.org/nodejs/readable-stream/builds/94369987, :+1:  from anyone in @nodejs/streams ?

**Comment by sonewman** [comment]
Sorry for a delayed response. LGTM :+1:

I was reading through some of the documentation, i think it would be good to revisit some bits, for instance the stream options lists does not include implementation methods.

We could also update the examples to use es2015/6 features now available in Node like classes, shorthand object methods, etc.

Anyway, merging...

**Comment by calvinmetcalf** [comment]
thanks, published as v2.0.5

**Pull request merged**
