### PR TITLE
re-add WriteReq and CorkedRequest constructors

### PR DESCRIPTION
**Pull request by mscdex**
This PR is in anticipation of https://github.com/nodejs/node/pull/10558 (do not land this before the node core PR).

Also, this should land *before* https://github.com/nodejs/readable-stream/pull/253 so that the replacements are done in the correct order.

/cc @mcollina

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
so once  nodejs/node#10558  lands I'll try merging in this and #253

**Comment by calvinmetcalf** [comment]
so I've got a couple questions

1. is this that the perf benefits of object literals vs constructors have changed in more recent versions of v8 or is it that better perfing has shown that object literals were better all along
2. why is this beneficial in node core but NOT in readable stream?

have been out of the loop the last week or 2 so sorry if this has been answered already

**Comment by mcollina** [comment]
> is this that the perf benefits of object literals vs constructors have changed in more recent versions of v8 or is it that better perfing has shown that object literals were better all along

Only most recent versions

> why is this beneficial in node core but NOT in readable stream?

It will cause a slowdown for older node versions.

**Comment by mcollina** [comment]
Part of #262

**Comment by mcollina** [comment]
Merging this have been a mistake. This should be merged when Node.js hits v8.0.0, as the the HTTP changes lands.

**Comment by calvinmetcalf** [comment]
@mcollina there is a merge conflict here, can you rebase it ?

**Comment by mcollina** [comment]
we need this for https://github.com/nodejs/readable-stream/pull/290. I'll see what I can do but I am traveling this week.

**Comment by calvinmetcalf** [comment]
ok I can probably do it too, I'm not 100% on it though like how many libraries are using corked writable streams in the hot path and in older node using readable-streams. Wouldn't they also be having similar if not bigger performance issues from using that older node and they'd get bigger benefits from upgrading ?

**Comment by mcollina** [comment]
Closing as it is now part of #290.

**Pull request closed without merging**
