### PR TITLE
Build for Deno

### PR DESCRIPTION
**Pull request by Soremwar**
Discussion in #451 

This needs some polishing, namely:

- [ ] Enable tests to work based on the Deno build
- [ ] Await some of my PRs to be merged into Deno repo that fix some issues with their current Node polyfill
- [ ] Discuss method of publishing, and talk about mantainability for the future
- [ ] Document Deno polyfills
- [ ] Document Crossplatform variables and modules

### CODE REVIEW

**Comment by Soremwar** [comment]
Anyone that can help me debug this fails? I tried to test them on Node 6.17.1 and they all passed

**Review by mcollina — CHANGES_REQUESTED** [review]
The changes done inside `lib` must be done inside `build/` instead. There is a bunch of scripts there that takes code from Node.js core and rewrite it so it's agnostics. We could potentially use some of the same machinery to generate a deno build.

**Comment by mcollina** [comment]
(Unfortunately I do not have time to debug the build right now, I'm going for some extended leave and I'll be back full time next year).

**Comment by benjamingr** [comment]
@mcollina can you point me at the code that generates readable-stream from Node core? I'm not actually familiar with it :]?

**Comment by targos** [comment]
@benjamingr https://github.com/nodejs/readable-stream/blob/master/build/build.js

**Comment by Soremwar** [comment]
Someone knows what version of Node the last build of readable stream is using? The README points out to it being Node 10 but I can't really tell.

**Comment by benjamingr** [comment]
Looking at the issue I think it's v10.18.1

**Comment by Soremwar** [comment]
Thanks @benjamingr

**Comment by mcollina** [comment]
This seems pretty amazing! Are there any tests for this?

**Comment by Soremwar** [comment]
@mcollina Actually...that's the main reason why there's been so little activity in this since it was created. The build has been working for a while, but making the tests work has proven to be a major headache due to the differences between the Deno test suite and something like tap

More progress to follow though, I'm on vacations so I land put some time on this

**Comment by mcollina** [comment]
You can also write a few high level tests. We run separate tests for the browser for this reason, see https://github.com/nodejs/readable-stream/tree/master/test/browser for more details.

**Comment by mcollina** [comment]
FYI: check out https://github.com/nodejs/readable-stream/pull/454.

**Comment by jimmywarting** [comment]
I doubt that Deno won't get much traction for node streams, they are mostly just focused on web standarder, meaning: whatwg streams. Node also recently got them.

I always try to avoid core builtin's when i develop anything for cross platform that runs in Deno, Browser and Node.
I never want to bundle the hole readable-stream into the browser, it cost too much, I always try to make my page score 100% in lighthouse
i got a own size limit to somewhere like < 100 kb when i develop a js library for browser and node:stream can easily break that threshold

**Pull request closed without merging**
