### PR TITLE
fix undefined global for browser / service worker (v2.x branch)

### PR DESCRIPTION
**Pull request by smeng9**
@mcollina

Supersedes https://github.com/nodejs/readable-stream/pull/493

Still need a v3.x branch to target at

### CODE REVIEW

**Comment by smeng9** [comment]
Any updates?

**Comment by smeng9** [comment]
@mcollina Bump

**Comment by mcollina** [comment]
I'm currently swamped. I'll get to this as soon as I have time.

**Comment by mcollina** [comment]
I've created the v3.x branch. Could you send a PR there too?

**Comment by smeng9** [comment]
Sure!

**Comment by smeng9** [comment]
Hi @mcollina,

Considering that 97.89% of [downloads of readable-stream on npmjs](https://www.npmjs.com/package/readable-stream?activeTab=versions) still uses the pre 4.x version. Is it possible to get the fix for older versions merged soon as the adoption rate is slow for a major update.

Thanks!

**Pull request merged**
