### PR TITLE
fix for sync writes in older node

### PR DESCRIPTION
**Pull request by calvinmetcalf**
possible fix for #187

### CODE REVIEW

**Comment by mcollina** [comment]
BTW, we should really use `setImmediate` with 0.10.

```
$ node -v
v0.10.41
~/Repositories/fastbench (master)
$ node example.js
benchSetTimeout*1000: 1333ms
benchSetImmediate*1000: 4ms
benchSetTimeout*1000: 1327ms
benchSetImmediate*1000: 3ms
```

**Comment by calvinmetcalf** [comment]
setImmediate is not available in node 0.10

**Comment by mcollina** [comment]
I think `setImmediate` was introduced in v0.10

```
$ node -v
v0.10.41
~
$ node
> setImmediate(console.log, 'hello world')
{ _idleNext:
   { _idleNext: [Circular],
     _idlePrev: [Circular] },
  _idlePrev:
   { _idleNext: [Circular],
     _idlePrev: [Circular] },
  _onImmediate: [Function] }
> hello world

undefined
>
(^C again to quit)
> ~
$
```

**Comment by calvinmetcalf** [comment]
hm in that case, that will simplify things

**Comment by calvinmetcalf** [comment]
I am happy to be wrong about this :smile:

**Comment by calvinmetcalf** [comment]
how do we feel about this one?

**Comment by mcollina** [comment]
LGTM

**Comment by calvinmetcalf** [comment]
rebased will merge when green

**Pull request merged**
