### PR TITLE
Removed numeric separator

### PR DESCRIPTION
**Pull request by jaxoncreed**
This is a simple pull request that removes the numeric separator from validators.js.

While the numeric separator is nicer to look at, it causes problems when this library is used in React-Native's default configuration. https://github.com/facebook/metro/issues/645. It is possible to change the default configuration manually, but that's overhead for a developer. To make it easier to install developer tooling that uses readable-stream it would be great to remove the numeric separators.

### CODE REVIEW

**Comment by mcollina** [comment]
Could you make this change inside the `build/` scripts?

**Comment by jaxoncreed** [comment]
Ah I see. I've added it to the "replacements" file. Though, I'm unsure if I ran the build script properly as many files have minor style changes. Is there an instruction guide anywhere for running the build script?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
@ShogunPanda PTAL

**Comment by ShogunPanda** [comment]
Also looks good to me in regard of changes in the `build` folder.
All other changes are mostly not needed.

@jaxoncreed can you please do the following?

1. Reset your branch to the last master commit and only keep the change in the `build` Folder.
2. Run `nom run build 18.9.0`

After that you should only get the relevant change and then you can force push the branch.

**Comment by vweevers** [comment]
It's mostly whitespace changes, I would guess there was some fix in babel or prettier that changes the output here.

**Comment by jaxoncreed** [comment]
Is this okay to merge then? Is there anything else I should do?

**Comment by jaxoncreed** [comment]
Hi all, just want to bump this. Can it be merged in?

**Comment by ShogunPanda** [comment]
Can you please rebase and solve merge conflicts?

**Comment by jaxoncreed** [comment]
Thanks @ShogunPanda I've rebased and solved merge conflicts

**Comment by ShogunPanda** [comment]
@mcollina This LGTM. I think you can now have the CI run and then merge.

**Review by ShogunPanda — APPROVED** [review]

**Comment by jaxoncreed** [comment]
Hi all. Just bumping this again to see if it can be merged in.

**Comment by mcollina** [comment]
I'm a bit swamped atm. Releasing readable-stream is always a potentially dangerous operation (given the amount of downloads) that I want to do with great care.

It's on the list.

**Comment by jaxoncreed** [comment]
Hey, sorry to pester again. Just want to see if there's a timeline for merging this in.

**Comment by moki** [comment]
breaks tar-stream@^3 for me

**Comment by mcollina** [comment]
@moki how? did you have a repro?

**Comment by jaxoncreed** [comment]
Thank you

**Pull request merged**
