### PR TITLE
Simpler event stream sub

### PR DESCRIPTION
**Pull request by calvinmetcalf**
fix for #277, hopfully

### CODE REVIEW

**Comment by mcollina** [comment]
LGTM and let's see what happens.

**Comment by calvinmetcalf** [comment]
wait actually I have a better idea

**Comment by calvinmetcalf** [comment]
we already are successfully using the package.browser switch, so lets use it for this

**Comment by calvinmetcalf** [comment]
ok @mcollina check this out

**Comment by RangerMauve** [comment]
@calvinmetcalf You'll want to apply these changes to the `react-native` field, too, or get rid of it to use the browser version instead.

**Comment by calvinmetcalf** [comment]
ok good call

**Comment by RangerMauve** [comment]
Err, wait, it'll still bark on loading the `stream` module. Maybe copy the whole browser object, and for React-Native add `"stream": false`. Since it needs all the changes for browser compatibility, plus it needs the stream module to be explicitly excluded, else the `require("st" + "ream")` call will crash the bundler.

**Comment by calvinmetcalf** [comment]
there shouldn't be any stream calls anymore in the browser code

**Comment by RangerMauve** [comment]
You're right, sorry about that. :P

**Comment by calvinmetcalf** [comment]
so it's good ?

**Comment by calvinmetcalf** [comment]
@mcollina the idea isn't that we need the same api, it's that `instanceof stream` checks should succeed

**Comment by mcollina** [comment]
LGTM

**Pull request merged**
