### PR TITLE
use container-based infrastructure for faster build

### PR DESCRIPTION
**Pull request by shinnn**
http://docs.travis-ci.com/user/workers/container-based-infrastructure/

### CODE REVIEW

**Comment by calvinmetcalf** [comment]
do you mind rebasing it off of #139 to make sure it works there ?

**Comment by dcousens** [comment]
@shinnn it seems odd this isn't the default behaviour...

**Comment by calvinmetcalf** [comment]
I think the idea is that it will be at some point

**Comment by calvinmetcalf** [comment]
e3bf6c54e98b2241020be0d84721e5254214b84e

**Comment by shinnn** [comment]
:+1:

**Comment by shinnn** [comment]
@dcousens 

> it seems odd this isn't the default behaviour...

`sudo: false` by default breaks a lot of builds since various projects include `sudo apt get [something]` in their build scripts.

**Comment by dcousens** [comment]
@shinnn then maybe the script should look for `sudo` and assume `sudo: false` if it doesn't exist?

**Comment by shinnn** [comment]
Good idea! :point_right: https://github.com/travis-ci/travis-ci/issues

**Pull request closed without merging**
