### PR TITLE
Array.isArray() and Object.keys() shims

### PR DESCRIPTION
**Pull request by ghost**
With these hacks, we can hopefully get to es3 compat and I'll switch over stream-browserify to use readable-stream directly instead, saving many bytes in mixed `require('stream')` vs `require('readable-stream')` usage.

### CODE REVIEW

**Comment by f0rmat1k** [comment]
You still need es3?

**Comment by mcollina** [comment]
@f0rmat1k yes we do until we bump the major, as it is a semver-major change.

**Comment by f0rmat1k** [comment]
@mcollina ok. Are you gonna to release such major? I can send PR. It's just rly strange to see in 2017 `isarray` dependency, when you install such pockets as mongodb for example.

**Comment by mcollina** [comment]
@f0rmat1k at the moment there is no plan to release a semver major change any time soon.

**Pull request merged**
