### PR TITLE
build for 5.9.1

### PR DESCRIPTION
**Pull request by calvinmetcalf**
this is one is pretty strait forward

### CODE REVIEW

**Comment by mcollina** [comment]
:+1:

**Comment by calvinmetcalf** [comment]
wait knew that was too easy, github changed the classes in the table so our script broke, that being said, nothing actually changed

**Comment by mcollina** [comment]
even better :).

**Comment by phillipj** [comment]
Woopsie, ignore that comment... Some testing going on here :)

**Pull request merged**
